<?php

// if not included correctly...
if ( !class_exists( 'WpSecurityAuditLog' ) ) exit();

defined('E_CRITICAL') || define('E_CRITICAL', 'E_CRITICAL');
defined('E_DEBUG') || define('E_DEBUG', 'E_DEBUG');

WpSecurityAuditLog::GetInstance()
	->constants->UseConstants(array(
		// default PHP constants
		array('name' => 'E_ERROR', 'description' => __('Fatal run-time error.')),
		array('name' => 'E_WARNING', 'description' => __('Run-time warning (non-fatal error).')),
		array('name' => 'E_PARSE', 'description' => __('Compile-time parse error.')),
		array('name' => 'E_NOTICE', 'description' => __('Run-time notice.')),
		array('name' => 'E_CORE_ERROR', 'description' => __('Fatal error that occurred during startup.')),
		array('name' => 'E_CORE_WARNING', 'description' => __('Warnings that occurred during startup.')),
		array('name' => 'E_COMPILE_ERROR', 'description' => __('Fatal compile-time error.')),
		array('name' => 'E_COMPILE_WARNING', 'description' => __('Compile-time warning.')),
		array('name' => 'E_USER_ERROR', 'description' => __('User-generated error message.')),
		array('name' => 'E_USER_WARNING', 'description' => __('User-generated warning message.')),
		array('name' => 'E_USER_NOTICE', 'description' => __('User-generated notice message. ')),
		array('name' => 'E_STRICT', 'description' => __('Non-standard/optimal code warning.')),
		array('name' => 'E_RECOVERABLE_ERROR', 'description' => __('Catchable fatal error.')),
		array('name' => 'E_DEPRECATED', 'description' => __('Run-time deprecation notices.')),
		array('name' => 'E_USER_DEPRECATED', 'description' => __('Run-time user deprecation notices.')),
		// custom constants
		array('name' => 'E_CRITICAL', 'description' => __('Critical, high-impact messages.')),
		array('name' => 'E_DEBUG', 'description' => __('Debug informational messages.')),
	));

WpSecurityAuditLog::GetInstance()
	->alerts->RegisterGroup(array(
		'Other User Activity' => array(
			array(1000, E_NOTICE, __('User logs in'), __('Successfully logged in')),
			array(1001, E_NOTICE, __('User logs out'), __('Successfully logged out')),
			array(1002, E_WARNING, __('Login failed'), __('%Attempts% failed login(s) detected')),
			array(2010, E_NOTICE, __('User uploaded file from Uploads directory'), __('Uploaded the file %FileName% in %FilePath%')),
			array(2011, E_WARNING, __('User deleted file from Uploads directory'), __('Deleted the file %FileName% from %FilePath%')),
			array(2046, E_CRITICAL, __('User changed a file using the editor'), __('Modified %File% with the Theme Editor')),
		),
		'Blog Posts' => array(
			array(2000, E_NOTICE, __('User created a new blog post and saved it as draft'), __('Created a new blog post called %PostTitle%. Blog post ID is %PostID%')),
			array(2001, E_NOTICE, __('User published a blog post'), __('Published a blog post called %PostTitle%. Blog post URL is %PostUrl%')),
			array(2002, E_NOTICE, __('User modified a published blog post'), __('Modified the published blog post %PostTitle%. Blog post URL is %PostUrl%')),
			array(2003, E_NOTICE, __('User modified a draft blog post'), __('Modified the draft blog post %PostTitle%. Blog post ID is %PostID%')),
			array(2008, E_NOTICE, __('User permanently deleted a blog post from the trash'), __('Deleted the post %PostTitle%. Blog post ID is %PostID%')),
			array(2012, E_WARNING, __('User moved a blog post to the trash'), __('Moved the blog post %PostTitle% to trash')),
			array(2014, E_CRITICAL, __('User restored a blog post from trash'), __('Restored post %PostTitle% from trash')),
			array(2016, E_NOTICE, __('User changed blog post category'), __('Changed the category of the post %PostTitle% from %OldCategories% to %NewCategories%')),
			array(2017, E_NOTICE, __('User changed blog post URL'), __('Changed the URL of the post %PostTitle% from %OldUrl% to %NewUrl%')),
			array(2019, E_NOTICE, __('User changed blog post author'), __('Changed the author of %PostTitle% post from %OldAuthor% to %NewAuthor%')),
			array(2021, E_NOTICE, __('User changed blog post status'), __('Changed the status of %PostTitle% post from %OldStatus% to %NewStatus%')),
			array(2023, E_NOTICE, __('User created new category'), __('Created a new category called %CategoryName%')),
			array(2024, E_WARNING, __('User deleted category'), __('Deleted the %CategoryName% category')),
			array(2025, E_WARNING, __('User changed the visibility of a blog post'), __('Changed the visibility of %PostTitle% blog post  from %OldVisibility% to %NewVisibility%')),
			array(2027, E_NOTICE, __('User changed the date of a blog post'), __('Changed the date of %PostTitle% blog post from %OldDate% to %NewDate%')),
			array(2049, E_NOTICE, __('User sets a post as sticky'), __('Set the post %PostTitle% as Sticky')),
			array(2050, E_NOTICE, __('User removes post from sticky'), __('Removed the post %PostTitle% from Sticky')),
		),
		'Pages' => array(
			array(2004, E_NOTICE, __('User created a new WordPress page and saved it as draft'), __('Created a new page called %PostTitle%. Page ID is %PostID%')),
			array(2005, E_NOTICE, __('User published a WorPress page'), __('Published a page called %PostTitle%. Page URL is %PostUrl%')),
			array(2006, E_NOTICE, __('User modified a published WordPress page'), __('Modified the published page %PostTitle%. Page URL is %PostUrl%')),
			array(2007, E_NOTICE, __('User modified a draft WordPress page'), __('Modified the draft page %PostTitle%. page ID is %PostID%')),
			array(2009, E_NOTICE, __('User permanently deleted a page from the trash'), __('Deleted the page %PostTitle%. Page ID is %PostID%')),
			array(2013, E_WARNING, __('User moved WordPress page to the trash'), __('Moved the page %PostTitle% to trash')),
			array(2015, E_CRITICAL, __('User restored a WordPress page from trash'), __('Restored page %PostTitle% from trash')),
			array(2018, E_NOTICE, __('User changed page URL'), __('Changed the URL of the page %PostTitle% from %OldUrl% to %NewUrl%')),
			array(2020, E_NOTICE, __('User changed page author'), __('Changed the author of %PostTitle% page from %OldAuthor% to %NewAuthor%')),
			array(2022, E_NOTICE, __('User changed page status'), __('Changed the status of %PostTitle% page from %OldStatus% to %NewStatus%')),
			array(2026, E_WARNING, __('User changed the visibility of a page post'), __('Changed the visibility of %PostTitle% page  from %OldVisibility% to %NewVisibility%')),
			array(2028, E_NOTICE, __('User changed the date of a page post'), __('Changed the date of %PostTitle% page from %OldDate% to %NewDate%')),
			array(2047, E_NOTICE, __('User changed the parent of a page'), __('Changed the parent of %PostTitle% page from %OldParentName% to %NewParentName%')),
			array(2048, E_CRITICAL, __('User changes the template of a page'), __('Changed the template of %PostTitle% page from %OldTemplate% to %NewTemplate%')),
		),
		'Custom Posts' => array(
			array(2029, E_NOTICE, __('User created a new post with custom post type and saved it as draft'), __('Created a new custom post called %PostTitle% of type %PostType%. Post ID is %PostID%')),
			array(2030, E_NOTICE, __('User published a post with custom post type'), __('Published a custom post %PostTitle% of type %PostType%. Post URL is %PostUrl%')),
			array(2031, E_NOTICE, __('User modified a post with custom post type'), __('Modified custom post %PostTitle% of type %PostType%. Post URL is %PostUrl%')),
			array(2032, E_NOTICE, __('User modified a draft post with custom post type'), __('Modified draft custom post %PostTitle% of type is %PostType%. Post URL is %PostUrl%')),
			array(2033, E_WARNING, __('User permanently deleted post with custom post type'), __('Deleted custom post %PostTitle% of type %PostType%')),
			array(2034, E_WARNING, __('User moved post with custom post type to trash'), __('Moved custom post %PostTitle% to trash. Post type is %PostType%')),
			array(2035, E_CRITICAL, __('User restored post with custom post type from trash'), __('Restored custom post %PostTitle% of type %PostType% from trash')),
			array(2036, E_NOTICE, __('User changed the category of a post with custom post type'), __('Changed the category(ies) of custom post %PostTitle% of type %PostType% from %OldCategories% to %NewCategories%')),
			array(2037, E_NOTICE, __('User changed the URL of a post with custom post type'), __('Changed the URL of custom post %PostTitle% of type %PostType% from %OldUrl% to %NewUrl%')),
			array(2038, E_NOTICE, __('User changed the author or post with custom post type'), __('Changed the author of custom post %PostTitle% of type %PostType% from %OldAuthor% to %NewAuthor%')),
			array(2039, E_NOTICE, __('User changed the status of post with custom post type'), __('Changed the status of custom post %PostTitle% of type %PostType% from %OldStatus% to %NewStatus%')),
			array(2040, E_WARNING, __('User changed the visibility of a post with custom post type'), __('Changed the visibility of custom post %PostTitle% of type %PostType% from %OldVisibility% to %NewVisibility%')),
			array(2041, E_NOTICE, __('User changed the date of post with custom post type'), __('Changed the date of custom post %PostTitle% of type %PostType% from %OldDate% to %NewDate%')),
		),
		'Widgets' => array(
			array(2042, E_CRITICAL, __('User added a new widget'), __('Added a new %WidgetName% widget in  %Sidebar%')),
			array(2043, E_WARNING, __('User modified a widget'), __('Modified the %WidgetName% widget in %Sidebar%')),
			array(2044, E_CRITICAL, __('User deleted widget'), __('Deleted the %WidgetName% widget from %Sidebar%')),
			array(2045, E_NOTICE, __('User moved widget'), __('Moved the %WidgetName% widget from %OldSidebar% to %NewSidebar%')),
		),
		'User Profiles' => array(
			array(4000, E_CRITICAL, __('A new user was created on WordPress'), __('User %NewUserData->Username% subscribed with a role of %NewUserData->Roles%')),
			array(4001, E_CRITICAL, __('A user created another WordPress user'), __('Created a new user %NewUserData->Username% with the role of %NewUserData->Roles%')),
			array(4002, E_CRITICAL, __('The role of a user was changed by another WordPress user'), __('Changed the role of user %TargetUsername% from %OldRole% to %NewRole%')),
			array(4003, E_CRITICAL, __('User has changed his or her password'), __('Changed the password')),
			array(4004, E_CRITICAL, __('A user changed another user\'s password'), __('Changed the password for user %TargetUserData->Username% with the role of %TargetUserData->Roles%')),
			array(4005, E_NOTICE, __('User changed his or her email address'), __('Changed the email address from %OldEmail% to %NewEmail%')),
			array(4006, E_NOTICE, __('A user changed another user\'s email address'), __('Changed the email address of user account %TargetUsername% from %OldEmail% to %NewEmail%')),
			array(4007, E_CRITICAL, __('A user was deleted by another user'), __('Deleted User %TargetUserData->Username% with the role of %TargetUserData->Roles%')),
		),
		'Plugins & Themes' => array(
			array(5000, E_CRITICAL, __('User installed a plugin'), __('Installed the plugin %NewPlugin->Name% in %NewPlugin->plugin_dir_path%')),
			array(5001, E_CRITICAL, __('User activated a WordPress plugin'), __('Activated the plugin %PluginData->Name% installed in %PluginFile%')),
			array(5002, E_CRITICAL, __('User deactivated a WordPress plugin'), __('Deactivated the plugin %PluginData->Name% installed in %PluginFile%')),
			array(5003, E_CRITICAL, __('User uninstalled a plugin'), __('Uninstalled the plugin %PluginData->Name% which was installed in %PluginFile%')),
			array(5004, E_WARNING, __('User upgraded a plugin'), __('Upgraded the plugin %PluginData->Name% installed in %PluginFile%')),
			array(5005, E_CRITICAL, __('User installed a theme'), __('Installed theme "%NewTheme->Name%" in %NewTheme->get_template_directory%')),
			array(5006, E_CRITICAL, __('User activated a theme'), __('Activated theme "%NewTheme->Name%", installed in %NewTheme->get_template_directory%')),
		),
		'System Activity' => array(
			array(0000, E_CRITICAL, __('Unknown Error'), __('An unexpected error has occurred')),
			array(0001, E_CRITICAL, __('PHP error'), __('%Message%')),
			array(0002, E_WARNING, __('PHP warning'), __('%Message%')),
			array(0003, E_NOTICE, __('PHP notice'), __('%Message%')),
			array(0004, E_CRITICAL, __('PHP exception'), __('%Message%')),
			array(0005, E_CRITICAL, __('PHP shutdown error'), __('%Message%')),
			array(6000, E_NOTICE, __('Events automatically pruned by system'), __('%EventCount% event(s) automatically deleted by system')),
			array(6001, E_CRITICAL, __('Option Anyone Can Register in WordPress settings changed'), __('%NewValue% the option "Anyone can register"')),
			array(6002, E_CRITICAL, __('New User Default Role changed'), __('Changed the New User Default Role from %OldRole% to %NewRole%')),
			array(6003, E_CRITICAL, __('WordPress Administrator Notification email changed'), __('Changed the WordPress administrator notifications email address from %OldEmail% to %NewEmail%')),
			array(6004, E_CRITICAL, __('WordPress was updated'), __('Updated WordPress from version %OldVersion% to %NewVersion%')),
			array(6005, E_CRITICAL, __('User changes the WordPress Permalinks'), __('Changed the WordPress permalinks from %OldPattern% to %NewPattern%')),
		),
		'MultiSite' => array(
			array(4008, E_CRITICAL, __('User granted Super Admin privileges'), __('Granted Super Admin privileges to %TargetUsername%')),
			array(4009, E_CRITICAL, __('User revoked from Super Admin privileges'), __('Revoked Super Admin privileges from %TargetUsername%')),
			array(4010, E_CRITICAL, __('Existing user added to a site'), __('Added existing user %TargetUsername% with %TargetUserRole% role to site %SiteName%')),
			array(4011, E_CRITICAL, __('User removed from site'), __('Removed user %TargetUsername% with role %TargetUserRole% from %SiteName% site')),
			array(4012, E_CRITICAL, __('New network user created'), __('Created a new network user %NewUserData->Username%')),
			array(7000, E_CRITICAL, __('New site added on network'), __('Added site %SiteName% to the network')),
			array(7001, E_CRITICAL, __('Existing site archived'), __('Archived site %SiteName%')),
			array(7002, E_CRITICAL, __('Archived site has been unarchived'), __('Unarchived site %SiteName%')),
			array(7003, E_CRITICAL, __('Deactivated site has been activated'), __('Activated site %SiteName%')),
			array(7004, E_CRITICAL, __('Site has been deactivated'), __('Deactivated site %SiteName%')),
			array(7005, E_CRITICAL, __('Existing site deleted from network'), __('Deleted site %SiteName%')),
		),
	));
