<?php
/**
 * View: About
 *
 * WSAL about page.
 *
 * @since 1.0.0
 * @package Wsal
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * About Page.
 *
 * @package Wsal
 */
class WSAL_Views_About extends WSAL_AbstractView {

	/**
	 * Method: Get View Title.
	 */
	public function GetTitle() {
		return __( 'About WP Security Audit Log', 'wp-security-audit-log' );
	}

	/**
	 * Method: Get View Icon.
	 */
	public function GetIcon() {
		return 'dashicons-editor-help';
	}

	/**
	 * Method: Get View Name.
	 */
	public function GetName() {
		return __( 'About', 'wp-security-audit-log' );
	}

	/**
	 * Method: Get View Weight.
	 */
	public function GetWeight() {
		return 15;
	}

	/**
	 * Method: Get View.
	 */
	public function Render() {
		?>
		<div class="metabox-holder" style="position: relative;">
			<div class="postbox" style="margin-right: 270px;">
				<!--h3 class="hndl"><span>About WP Security Audit Log</span></h3-->
				<div class="inside">
					<div class="activity-block">
						<?php esc_html_e( 'WP Security Audit Log enables WordPress administrators and owners to identify WordPress security issues before they become a security problem by keeping a security audit log. WP Security Audit Log is developed by WordPress security professionals WP White Security.', 'wp-security-audit-log' ); ?>
						<h2><?php esc_html_e( 'Keep A WordPress Security Audit Log & Identify WordPress Security Issues', 'wp-security-audit-log' ); ?></h2>
						<p>
							<?php esc_html_e( 'WP Security Audit Log logs everything happening on your WordPress blog or website and WordPress multisite network. By using WP Security Audit Log security plugin it is very easy to track suspicious user activity before it becomes a problem or a security issue. A WordPress security alert is generated by the plugin when:', 'wp-security-audit-log' ); ?>
						</p>
						<ul style="list-style-type: disc; margin-left: 2.5em; list-style-position: outside;">
							<li><?php esc_html_e( 'User creates a new user or a new user is registered', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'Existing user changes the role, password or other properties of another user', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'Existing user on a WordPress multisite network is added to a site', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'User uploads or deletes a file, changes a password or email address', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'User installs, activates, deactivates, upgrades or uninstalls a plugin', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'User creates, modifies or deletes a new post, page, category or a custom post type', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'User installs or activates a WordPress theme', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'User adds, modifies or deletes a widget', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'User uses the dashboard file editor', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'WordPress settings are changed', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'Failed login attempts', 'wp-security-audit-log' ); ?></li>
							<li><?php esc_html_e( 'and much more&hellip;', 'wp-security-audit-log' ); ?></li>
						</ul>
						<br/>
						Refer to the complete list of <a href="http://www.wpsecurityauditlog.com/documentation/list-monitoring-wordpress-security-alerts-audit-log/?utm_source=wsalabt&amp;utm_medium=txtlink&amp;utm_campaign=wsal" target="_blank">WordPress Security Alerts</a> for more information.
					</div>
				</div>
			</div>

			<div style="position: absolute; right: 70px; width: 180px; top: 10px;">
				<div class="postbox">
					<h3 class="hndl"><span><?php esc_html_e( 'Extend the Functionality & Get More Value from WP Security Audit Log', 'wp-security-audit-log' ); ?></span></h3>
					<div class="inside">
						<p>
							<?php esc_html_e( 'Get more value out of WP Security Audit Log by extending the functionality of WP Security Audit Log with the premium Add-Ons.' ); ?>
						</p>
						<a class="button button-primary" href="http://www.wpsecurityauditlog.com/plugin-extensions/" target="_blank"><?php esc_html_e( 'See Add-Ons', 'wp-security-audit-log' ); ?></a>
					</div>
				</div>
				<div class="postbox">
					<h3 class="hndl"><span><?php esc_html_e( 'WP Security Audit Log in your Language!', 'wp-security-audit-log' ); ?></span></h3>
					<div class="inside">
						<?php esc_html_e( 'If you are interested in translating our plugin please drop us an email on', 'wp-security-audit-log' ); ?>
						<a href="mailto:<?php echo esc_attr( antispambot( 'plugins@wpwhitesecurity.com' ) ); ?>"><?php echo esc_html( antispambot( 'plugins@wpwhitesecurity.com' ) ); ?></a>.
					</div>
				</div>
				<div class="postbox">
					<h3 class="hndl"><span><?php esc_html_e( 'WordPress Security Services', 'wp-security-audit-log' ); ?></span></h3>
					<div class="inside">
						<?php esc_html_e( 'Professional WordPress security services provided by WP White Security', 'wp-security-audit-log' ); ?>
						<ul>
							<li><a href="http://www.wpwhitesecurity.com/wordpress-security-services/wordpress-security-hardening/?utm_source=wpsalabt&amp;utm_medium=txtlink&amp;utm_campaign=wpsal" target="_blank"><?php esc_html_e( 'Security Hardening', 'wp-security-audit-log' ); ?></a></li>
							<li><a href="http://www.wpwhitesecurity.com/wordpress-security-services/wordpress-security-audit/?utm_source=wpsalabt&amp;utm_medium=txtlink&amp;utm_campaign=wpsal" target="_blank"><?php esc_html_e( 'Security Audit', 'wp-security-audit-log' ); ?></a></li>
							<li><a href="http://www.wpwhitesecurity.com/wordpress-security-services/wordpress-plugins-security-code-audit-review/?utm_source=wpsalabt&amp;utm_medium=txtlink&amp;utm_campaign=wpsal" target="_blank"><?php esc_html_e( 'Plugin Security Code Audit', 'wp-security-audit-log' ); ?></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<?php
	}
}
